### ISSUE TITLE
typo3 10 support?

### ISSUE THREAD

**Issue by X-Tender** [MamounAlsmaiel/flux_kesearch_indexer#1]
I made a Test if it runs on typo3 but the indexer didn't index anything. Even without the field configuration (wehre he should index all fields).
Did I made something wrong or does it really didn't work?

/e:
Ok it seems to wok when I add my CE to the "content element types which should be indexed" field of the Indexer. So it's not such a big difference to this solution https://github.com/BenjaminBeck/bdm_kesearchindexer_flux/issues/2

**Comment by MamounAlsmaiel** [comment]
I didn't test it in TYPO3 10 yet
Yes of course you have to add your CE to the content element types which should be indexed
see README.md

**Comment by X-Tender** [comment]
Oh snap, I total missed it. However, I can conform that it works on typo3 10 when you adjust this small deprecation.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85802-MoveFlexFormServiceFromEXTextbaseToEXTcore.html
