### ISSUE TITLE
Newer TYPO3 versions will require extension key in composer.json

### ISSUE THREAD

**Issue by tpinne** [MamounAlsmaiel/flux_kesearch_indexer#5]
Message during `composer install/update`:

> The TYPO3 extension package "mamounalsmaiel/flux-kesearch-indexer", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

The missing piece:

 ```
  "extra": {
    "typo3/cms": {
      "extension-key": "flux_kesearch_indexer"
    }
  }
```

**Comment by MamounAlsmaiel** [comment]
@X-Tender thank you for your PR

**Comment by tpinne** [comment]
Is there any chance you could release a new version that includes this change? Currently there is no way to get this via composer without referencing the master branch.

**Comment by MamounAlsmaiel** [comment]
actually i don't use the extension in my projects anymore because i don't use flux anymore either, so i don't make new releases anymore, but if i have time i will do it
